[
  ./flip-noice-keys-to-xn.patch
  ./flip-search-resume-and-search-replace.patch
  ./keymaps.patch
  ./lsp_keymaps.patch
  ./lualine.patch
  ./neotree.patch
  ./save-with-double-leader.patch
  ./set-mocha-flavor.patch
  ./telescope-keybinds.patch
]
